import { createSlideDraft } from './validators'

export const EDUCATION_EVENT_KEY = 'educacao-integral-integrada-bahia'

const guidedQuestions = [
  'Que educação a Bahia precisa construir hoje para responder aos desafios e às oportunidades?',
  'Como assegurar que território, origem social, raça, gênero ou condição econômica não determinem as oportunidades educacionais dos estudantes baianos?',
  'Como incorporar ciência, tecnologia e inteligência artificial à educação pública sem ampliar desigualdades e preservando sua dimensão humana, crítica e democrática?',
  'Como a educação pode contribuir para gerar oportunidades, reduzir desigualdades territoriais e fortalecer um modelo sustentável de desenvolvimento para a Bahia?',
  'Como construir uma relação permanente entre educação básica, universidades e instituições científicas para ampliar oportunidades e produzir conhecimento voltado aos desafios da Bahia?',
]

export const EDUCATION_EVENT = {
  key: EDUCATION_EVENT_KEY,
  title: 'Educação Integral e Integrada para o Desenvolvimento Econômico e Social da Bahia',
  shortTitle: 'Seminário Educação Integral Integrada',
  date: '15/09/2026',
  time: '13 às 17 horas',
  location: 'Auditório da SEC',
  organizer: 'Secretaria da Educação do Estado da Bahia',
  expectedAudience: '100 lideranças e representantes do ecossistema educacional baiano',
  methodology:
    'Mesa-redonda interinstitucional com escuta qualificada, diálogo entre os participantes e sistematização contínua das contribuições do público.',
  objective:
    'Elaborar coletivamente diretrizes estratégicas para o fortalecimento da educação pública na Bahia na perspectiva do desenvolvimento social e econômico a partir dos territórios da Bahia.',
  publicProfile: [
    'APLB, FEEBA, UNDIME, UNCME e CEE-BA',
    'Pró-Reitores das universidades estaduais e federais da Bahia e dos Institutos Federais (IFBA e IF Baiano)',
    'Diretores dos Núcleos Territoriais de Educação, gestores escolares e representantes de coordenação pedagógica',
    'CASA CIVIL, COJUV, SECTI, SDE, SEPROMI, SPM, SJDH, FAPESB, SETRE, SECULT, SEI, SEPLAN e SETUR',
  ],
  guidedQuestions,
  program: [
    { time: '13h', theme: 'Abertura', speakers: 'Mestre de cerimônia' },
    {
      time: '13h10',
      theme: 'Educação integral e integrada para o desenvolvimento econômico e social da Bahia',
      speakers: 'Marcius Gomes',
    },
    {
      time: '13h30',
      theme: 'O lugar da educação no desenvolvimento social, econômico, científico e territorial da Bahia',
      speakers: 'Claudio Peixoto (SEPLAN) e Adriana Marmori (UNEB)',
    },
    { time: '13h50', theme: 'Interação', speakers: 'Mediação — Nivaldo Milet' },
    {
      time: '14h',
      theme: 'Educação Básica, Ensino Superior e Produção do conhecimento',
      speakers: 'João Carlos (UFBA) e Anderson Passos (UNDIME)',
    },
    { time: '14h20', theme: 'Interação', speakers: 'Mediação — Nivaldo Milet' },
    {
      time: '14h30',
      theme: 'Garantia das aprendizagens e enfrentamento das desigualdades educacionais',
      speakers: 'Ângela Guimarães (SEPROMI), Felipe Freitas (SJDH) e Camila Batista (SPM)',
    },
    { time: '14h50', theme: 'Interação', speakers: 'Mediação — Direção de NTE' },
    {
      time: '15h',
      theme: 'Produção do conhecimento e soberania',
      speakers: 'Edson Porto (SECTI), Handerson Leite (FAPESB), Eracy Maciel (Casa Civil) e Manoel Barral (ACB)',
    },
    { time: '15h20', theme: 'Interação', speakers: 'Mediação — Nivaldo Milet' },
    {
      time: '15h30',
      theme: 'Formação, mundo do trabalho e desenvolvimento territorial sustentável',
      speakers: 'Augusto Vasconcelos (SETRE), Luzia Mota (IFBA) e SESI',
    },
    { time: '15h50', theme: 'Interação', speakers: 'Mediação — Direção de NTE' },
    { time: '16h', theme: 'Leitura da carta', speakers: 'Marcius Gomes' },
    { time: '16h10', theme: 'Encerramento', speakers: 'Mestre de cerimônia' },
  ],
  schools: [
    'CENTRO EDUCACIONAL CARNEIRO RIBEIRO - CLASSE I',
    'CENTRO EDUCACIONAL CARNEIRO RIBEIRO - ESCOLA PARQUE',
    'CENTRO EDUCACIONAL EDGAR SANTOS',
    'CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE E TECNOLOGIA DA INFORMACAO CARLOS CORREA DE MENEZES SANTANA',
    'CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO NEGOCIOS E TURISMO LUIZ NAVARRO DE BRITO',
    'CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM LOGISTICA E TRANSPORTE LUIZ PINTO DE CARVALHO',
    'COLEGIO ESTADUAL BARTOLOMEU DE GUSMAO',
    'COLEGIO ESTADUAL ALBERTO VALENCA - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL ANFRISIA SANTIAGO - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL BARROS BARRETO',
    'COLEGIO ESTADUAL CLARICE SANTIAGO',
    'COLEGIO ESTADUAL CLERISTON ANDRADE',
    'COLEGIO ESTADUAL DA BAHIA CENTRAL',
    'COLEGIO ESTADUAL DAVID MENDES PEREIRA',
    'COLEGIO ESTADUAL DE NOVA ESPERANCA',
    'COLEGIO ESTADUAL DE TEMPO INTEGRAL MINISTRO ALIOMAR BALEEIRO',
    'COLEGIO ESTADUAL DE TEMPO INTEGRAL VILA CANÁRIA',
    'COLEGIO ESTADUAL DE TEMPO INTEGRAL YPIRANGA',
    'COLEGIO ESTADUAL DE TEMPO INTEGRAL ZUMBI DOS PALMARES',
    'COLEGIO ESTADUAL DEMOCRATICO BERTHOLDO CIRILO DOS REIS',
    'COLEGIO ESTADUAL DO STIEP CARLOS MARIGHELLA',
    'COLEGIO ESTADUAL DOIS DE JULHO',
    'COLEGIO ESTADUAL DUQUE DE CAXIAS',
    'COLEGIO ESTADUAL EVARISTO DA VEIGA - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL GOES CALMON',
    'COLEGIO ESTADUAL GOVERNADOR LOMANTO JUNIOR',
    'COLEGIO ESTADUAL GOVERNADOR ROBERTO SANTOS',
    'COLEGIO ESTADUAL HELENA CELESTINO MAGALHAES',
    'COLEGIO ESTADUAL JOSE AUGUSTO TOURINHO DANTAS',
    'COLEGIO ESTADUAL LUIS VIANA',
    'COLEGIO ESTADUAL MANOEL DEVOTO',
    'COLEGIO ESTADUAL MARCILIO DIAS - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL MARILENE DA SILVA',
    'COLEGIO ESTADUAL MARIO AUGUSTO TEIXEIRA DE FREITAS',
    'COLEGIO ESTADUAL MARIO COSTA NETO',
    'COLEGIO ESTADUAL MESTRE PAULO DOS ANJOS',
    'COLEGIO ESTADUAL MINISTRO ALIOMAR BALEEIRO',
    'COLEGIO ESTADUAL NELSON MANDELA',
    'COLEGIO ESTADUAL NORMA RIBEIRO - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL PEDRO PAULO MARQUES E MARQUES',
    'COLEGIO ESTADUAL PRESIDENTE COSTA E SILVA',
    'COLEGIO ESTADUAL PROFESSOR CARLOS SANT ANNA - TEMPO INTEGRAL',
    'COLEGIO ESTADUAL PROFESSOR EDSON CARNEIRO',
    'COLEGIO ESTADUAL PROFESSOR ROMULO ALMEIDA',
    'COLEGIO ESTADUAL PROFESSORA MARIA BERNADETE BRANDAO',
    'COLEGIO ESTADUAL PROFESSORA NOEMIA REGO',
    'COLEGIO ESTADUAL RAYMUNDO DA MATA',
    'COLEGIO ESTADUAL RENAN BALEEIRO',
    'COLEGIO ESTADUAL ROTARY',
    'COLEGIO ESTADUAL SAO DANIEL COMBONI',
    'COLEGIO ESTADUAL SENHOR DO BONFIM',
    'COLEGIO ESTADUAL THALES DE AZEVEDO',
    'COLEGIO ESTADUAL VALE DOS LAGOS',
    'ESCOLA ESTADUAL DEPUTADO NAOMAR ALCANTARA - TEMPO INTEGRAL',
    'ESCOLA ESTADUAL NAOMAR ALCANTARA',
    'ESCOLA ESTADUAL PIERRE VERGER',
    'ESCOLA ESTADUAL PROFESSORA ARMANDINA MARQUES',
    'ESCOLA PRESCILIANO SILVA',
    'INSTITUTO CENTRAL DE EDUCACAO ISAIAS ALVES ICEIA',
  ],
  coordinators: [
    { name: 'Arielma Galvão', municipality: 'Salvador' },
    { name: 'Luciana Pita', municipality: 'Salvador' },
    { name: 'Bruna Gouveia', municipality: 'Salvador' },
    { name: 'Larissa Leslie', municipality: 'Salvador' },
    { name: 'Juliana Campos', municipality: 'Salvador' },
    { name: 'Simone Alves', municipality: 'Salvador' },
    { name: 'Ana Flávia', municipality: 'Salvador' },
    { name: 'Valuza Saraiva', municipality: 'Salvador' },
  ],
  coordinatorSourceNote:
    'A planilha informa “9 coordenadoras” no cabeçalho, mas contém 8 nomes preenchidos; a ata lista somente os nomes efetivamente fornecidos.',
}

const openQuestion = (question) => ({ ...createSlideDraft('open_text'), question })
const wordQuestion = (question) => ({ ...createSlideDraft('word_cloud'), question })

export const ATTENDANCE_INSTITUTIONS = Array.from(new Set([
  ...EDUCATION_EVENT.schools,
  'APLB',
  'FEEBA',
  'UNDIME',
  'UNCME',
  'CEE-BA',
  'UNEB',
  'UFBA',
  'Universidades estaduais da Bahia',
  'Universidades federais da Bahia',
  'IFBA',
  'IF Baiano',
  'Núcleos Territoriais de Educação (NTEs)',
  'Gestão escolar',
  'Coordenação pedagógica',
  'CASA CIVIL',
  'COJUV',
  'SECTI',
  'SDE',
  'SEPROMI',
  'SPM',
  'SJDH',
  'FAPESB',
  'SETRE',
  'SECULT',
  'SEI',
  'SEPLAN',
  'SETUR',
  'SEC',
  'SESI',
  'ACB',
])).sort((left, right) => left.localeCompare(right, 'pt-BR'))

export const isAttendanceInstitution = (value) => ATTENDANCE_INSTITUTIONS.includes(String(value ?? '').trim())

export const buildEducationEventSlides = () => [
  ...guidedQuestions.map(openQuestion),
  wordQuestion('Em uma palavra, qual legado este seminário deve deixar para a Educação da Bahia?'),
  openQuestion('Quais são os principais desafios que a Educação da Bahia precisa enfrentar?'),
  openQuestion('Quais prioridades estratégicas devem orientar a agenda da Educação da Bahia?'),
  openQuestion('Que proposições, compromissos ou próximos passos devem ser registrados para o futuro?'),
]

export const getEventData = (eventKey) => (eventKey === EDUCATION_EVENT_KEY ? EDUCATION_EVENT : null)
