import { createSlideDraft, createTeamDraft } from './validators'
import { TEAM_SELECTION_TYPE, COVER_TYPE, INTRODUCTION_TYPE, CLOSING_TYPE } from './constants'
import {
  AVANCA_EVENT,
  AVANCA_EVENT_KEY,
  EDUCATION_EVENT_KEY,
  EDUCATION_EVENT,
  buildAvancaEventSlides,
  buildEducationEventSlides,
} from './eventData'

const mc = (question, options) => ({ ...createSlideDraft('multiple_choice'), question, options: [...options] })
const wc = (question) => ({ ...createSlideDraft('word_cloud'), question })
const ot = (question) => ({ ...createSlideDraft('open_text'), question })
const ts = (question, teams) => ({
  ...createSlideDraft(TEAM_SELECTION_TYPE),
  question,
  teams: teams.map((t) => createTeamDraft(t.name, t.capacity)),
})
const staticSlide = (type, variant, content) => ({
  ...createSlideDraft(type),
  ...content,
  type,
  variant,
})

export const TEMPLATES = [
  {
    id: 'blank',
    name: 'Em branco',
    summary: 'Comece do zero com a etapa interativa mais popular.',
    accent: 'from-slate-500 to-slate-700',
    badge: 'Essencial',
    icon: 'sparkles',
    build: () => [
      {
        ...createSlideDraft('multiple_choice'),
        question: 'Qual a sua resposta?',
        options: ['Concordo totalmente', 'Concordo', 'Discordo', 'Discordo totalmente'],
      },
    ],
  },
  {
    id: 'cover-notebook',
    kind: 'static',
    name: 'Capa · Caderno de diálogo',
    summary: 'Uma abertura com espiral, papel pautado e espaço para o tema do encontro.',
    accent: 'from-amber-700 to-orange-300',
    badge: 'Capa',
    icon: 'book',
    build: () => [staticSlide(COVER_TYPE, 'notebook', {
      question: 'Caderno de ideias',
      eyebrow: 'Encontro de diálogo',
      subtitle: 'Escuta, reflexão e próximos passos',
      footer: 'Anote, compartilhe, transforme',
    })],
  },
  {
    id: 'cover-computer',
    kind: 'static',
    name: 'Capa · Computador 3D',
    summary: 'Uma tela em perspectiva para apresentar projetos e encontros digitais.',
    accent: 'from-slate-900 via-blue-800 to-cyan-500',
    badge: 'Capa',
    icon: 'monitor',
    build: () => [staticSlide(COVER_TYPE, 'computer', {
      question: 'Ideias em movimento',
      eyebrow: 'Conexão iniciada',
      subtitle: 'Um espaço para imaginar, testar e construir',
      footer: 'Projeto aberto · edição colaborativa',
    })],
  },
  {
    id: 'intro-editorial',
    kind: 'static',
    name: 'Introdução · Página tipográfica',
    summary: 'Contexto e pauta em uma grade de duas colunas, com poucos elementos e texto direto.',
    accent: 'from-stone-900 to-red-700',
    badge: 'Introdução',
    icon: 'sparkles',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'editorial', {
      question: 'Antes de começar',
      eyebrow: 'Contexto do encontro',
      subtitle: 'O problema que nos trouxe até aqui.',
      body: 'Vamos examinar o cenário, comparar propostas e sair com responsáveis definidos.',
      points: ['O que já funciona', 'Onde o processo trava', 'O que decidiremos hoje'],
      footer: 'Pauta aberta à contribuição',
    })],
  },
  {
    id: 'intro-computer',
    kind: 'static',
    name: 'Introdução · Tela de ideias',
    summary: 'Apresente o contexto e os objetivos dentro de uma estação de trabalho ilustrada.',
    accent: 'from-cyan-700 via-blue-800 to-indigo-950',
    badge: 'Introdução',
    icon: 'monitor',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'computer', {
      question: 'Carregando novas ideias',
      eyebrow: 'Estação colaborativa',
      subtitle: 'Hoje, a pauta é feita por quem participa.',
      body: 'Use este momento para compartilhar o que já sabemos e o que ainda precisamos descobrir.',
      points: ['Escuta ativa', 'Troca de experiências', 'Construção conjunta'],
      footer: 'Sessão iniciada',
    })],
  },
  {
    id: 'closing-spotlight',
    kind: 'static',
    name: 'Encerramento · Palco',
    summary: 'Feche o encontro com agradecimento e uma mensagem em destaque.',
    accent: 'from-indigo-950 via-violet-800 to-amber-500',
    badge: 'Encerramento',
    icon: 'sparkles',
    build: () => [staticSlide(CLOSING_TYPE, 'spotlight', {
      question: 'Obrigado por fazer parte',
      eyebrow: 'A conversa continua',
      subtitle: 'Toda boa ideia começa quando alguém compartilha.',
      body: 'Leve as descobertas de hoje para o próximo passo.',
      points: ['Registre o que ficou', 'Compartilhe com sua equipe'],
      footer: 'Até o próximo encontro',
    })],
  },
  {
    id: 'closing-computer',
    kind: 'static',
    name: 'Encerramento · Próximos passos',
    summary: 'Uma tela de computador para fechar a sessão e apontar o que vem a seguir.',
    accent: 'from-slate-900 via-teal-800 to-emerald-400',
    badge: 'Encerramento',
    icon: 'monitor',
    build: () => [staticSlide(CLOSING_TYPE, 'computer', {
      question: 'Próximos passos',
      eyebrow: 'Sessão concluída',
      subtitle: 'As ideias agora seguem para a prática.',
      body: 'Obrigado por contribuir com esta construção coletiva.',
      points: ['Organizar os registros', 'Definir responsáveis', 'Voltar para compartilhar avanços'],
      footer: 'Salvando boas ideias…',
    })],
  },
  {
    id: 'cover-editorial',
    kind: 'static',
    name: 'Capa · Cartaz tipográfico',
    summary: 'Tipografia grande, grade rigorosa e tinta vermelha sobre papel claro.',
    accent: 'from-red-700 to-stone-900',
    badge: 'Capa',
    icon: 'type',
    build: () => [staticSlide(COVER_TYPE, 'editorial', {
      question: 'Ideias em público',
      eyebrow: 'Encontro aberto',
      subtitle: 'Uma agenda construída com quem está aqui.',
      footer: 'Escuta coletiva · novos caminhos',
    })],
  },
  {
    id: 'cover-blueprint',
    kind: 'static',
    name: 'Capa · Prancha técnica',
    summary: 'Linhas de projeto, desenho isométrico e anotações em azul profundo.',
    accent: 'from-blue-950 to-sky-700',
    badge: 'Capa',
    icon: 'drafting',
    build: () => [staticSlide(COVER_TYPE, 'blueprint', {
      question: 'Projeto em construção',
      eyebrow: 'Prancha de abertura',
      subtitle: 'Do primeiro traço à construção coletiva.',
      footer: 'Hipóteses · testes · decisões',
    })],
  },
  {
    id: 'cover-zine',
    kind: 'static',
    name: 'Capa · Fanzine de recortes',
    summary: 'Papel, tinta e recortes para encontros mais experimentais.',
    accent: 'from-red-700 via-orange-400 to-stone-950',
    badge: 'Capa',
    icon: 'scissors',
    build: () => [staticSlide(COVER_TYPE, 'zine', {
      question: 'O que vem depois?',
      eyebrow: 'Edição coletiva',
      subtitle: 'Pessoas, caminhos e ideias em montagem.',
      footer: 'Rasgue o roteiro · comece a conversa',
    })],
  },
  {
    id: 'intro-folder',
    kind: 'static',
    name: 'Introdução · Pasta de projeto',
    summary: 'Um dossiê de trabalho com abas, ficha e objetivos numerados.',
    accent: 'from-amber-700 to-stone-700',
    badge: 'Introdução',
    icon: 'folder',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'folder', {
      question: 'O que está em jogo',
      eyebrow: 'Pasta de projeto',
      subtitle: 'Três perguntas para começar com clareza.',
      body: 'Reunimos o que já sabemos para decidir juntos o que precisa acontecer a seguir.',
      points: ['Qual é o desafio?', 'O que já aprendemos?', 'O que vamos decidir?'],
      footer: 'Arquivo aberto para contribuição',
    })],
  },
  {
    id: 'intro-timeline',
    kind: 'static',
    name: 'Introdução · Roteiro em etapas',
    summary: 'Uma linha do tempo clara para apresentar o percurso da conversa.',
    accent: 'from-stone-900 to-orange-600',
    badge: 'Introdução',
    icon: 'route',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'timeline', {
      question: 'Do diagnóstico à ação',
      eyebrow: 'Roteiro do encontro',
      subtitle: 'Um percurso simples para organizar o trabalho.',
      body: 'Cada etapa abre espaço para escutar, escolher e agir.',
      points: ['Reconhecer o cenário', 'Priorizar juntos', 'Combinar a próxima entrega'],
      footer: 'Avançamos uma etapa por vez',
    })],
  },
  {
    id: 'closing-credits',
    kind: 'static',
    name: 'Fechamento · Cartela de créditos',
    summary: 'Uma saída de cena com tipografia de cinema e mensagem central.',
    accent: 'from-neutral-950 to-neutral-700',
    badge: 'Encerramento',
    icon: 'film',
    build: () => [staticSlide(CLOSING_TYPE, 'credits', {
      question: 'A próxima cena é nossa',
      eyebrow: 'Fim da apresentação',
      subtitle: 'Obrigado a cada pessoa que participou.',
      body: 'O que construímos aqui continua nas escolhas de amanhã.',
      footer: 'Continua nas próximas ações',
    })],
  },
  {
    id: 'closing-receipt',
    kind: 'static',
    name: 'Fechamento · Recibo de ideias',
    summary: 'Um comprovante visual para guardar decisões e próximos passos.',
    accent: 'from-amber-700 to-stone-900',
    badge: 'Encerramento',
    icon: 'receipt',
    build: () => [staticSlide(CLOSING_TYPE, 'receipt', {
      question: 'Ficou combinado',
      eyebrow: 'Registro final',
      subtitle: 'O melhor resultado é o que seguimos fazendo.',
      body: 'Obrigado por construir este encontro.',
      points: ['Levar os aprendizados', 'Definir responsáveis', 'Retomar a conversa'],
      footer: 'Guarde este encontro',
    })],
  },
  {
    id: 'cover-newspaper',
    kind: 'static',
    name: 'Capa · Primeira página',
    summary: 'Manchete, filetes e colunas para abrir um encontro como notícia importante.',
    accent: 'from-stone-900 to-stone-500',
    badge: 'Capa',
    icon: 'type',
    build: () => [staticSlide(COVER_TYPE, 'newspaper', {
      question: 'Uma cidade em conversa',
      eyebrow: 'Jornal do encontro',
      subtitle: 'As ideias de hoje merecem sair da margem e ganhar a primeira página.',
      footer: 'Edição especial · voz coletiva',
    })],
  },
  {
    id: 'cover-contact-sheet',
    kind: 'static',
    name: 'Capa · Folha de contatos',
    summary: 'Quadros de filme, marcações de seleção e uma abertura com clima de arquivo fotográfico.',
    accent: 'from-zinc-950 to-amber-800',
    badge: 'Capa',
    icon: 'film',
    build: () => [staticSlide(COVER_TYPE, 'contact_sheet', {
      question: 'Novos olhares',
      eyebrow: 'Arquivo visual · 01',
      subtitle: 'Uma conversa pode mudar o enquadramento de tudo.',
      footer: 'Encontro em foco · edição aberta',
    })],
  },
  {
    id: 'intro-metro',
    kind: 'static',
    name: 'Introdução · Mapa de rotas',
    summary: 'Percurso com linhas e estações para explicar a agenda sem virar uma lista comum.',
    accent: 'from-blue-950 via-blue-700 to-orange-600',
    badge: 'Introdução',
    icon: 'route',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'metro', {
      question: 'O caminho de hoje',
      eyebrow: 'Linha do encontro',
      subtitle: 'Três paradas para chegar a uma decisão compartilhada.',
      body: 'Começamos pelo contexto, fazemos conexões e terminamos com uma direção clara.',
      points: ['Entender o cenário', 'Cruzar perspectivas', 'Escolher o próximo passo'],
      footer: 'Embarque nesta conversa',
    })],
  },
  {
    id: 'intro-catalog',
    kind: 'static',
    name: 'Introdução · Ficha de catálogo',
    summary: 'Uma ficha de acervo com campos catalogados para organizar tema, contexto e objetivos.',
    accent: 'from-emerald-950 to-amber-100',
    badge: 'Introdução',
    icon: 'folder',
    build: () => [staticSlide(INTRODUCTION_TYPE, 'catalog', {
      question: 'O que reunimos aqui',
      eyebrow: 'Ficha 001 · acervo de ideias',
      subtitle: 'Uma coleção de perguntas antes das respostas.',
      body: 'Esta ficha reúne os pontos de partida para que todos entrem na conversa com o mesmo contexto.',
      points: ['O desafio', 'As vozes presentes', 'O resultado esperado'],
      footer: 'Consulta aberta',
    })],
  },
  {
    id: 'closing-postcard',
    kind: 'static',
    name: 'Fechamento · Cartão-postal',
    summary: 'Uma mensagem de despedida para levar as ideias do encontro adiante.',
    accent: 'from-teal-900 to-rose-300',
    badge: 'Encerramento',
    icon: 'send',
    build: () => [staticSlide(CLOSING_TYPE, 'postcard', {
      question: 'Até a próxima conversa',
      eyebrow: 'Mensagem enviada',
      subtitle: 'Hoje foi só o começo.',
      body: 'Obrigado por dividir seu olhar. Leve uma ideia com você e faça-a circular.',
      footer: 'Destino: nossos próximos passos',
    })],
  },
  {
    id: EDUCATION_EVENT_KEY,
    name: EDUCATION_EVENT.shortTitle,
    summary: 'Roteiro institucional com as perguntas orientadoras, a escuta do público e a agenda da SEC.',
    accent: 'from-blue-700 to-cyan-500',
    badge: 'Evento especial',
    icon: 'landmark',
    eventKey: EDUCATION_EVENT_KEY,
    build: buildEducationEventSlides,
  },
  {
    id: AVANCA_EVENT_KEY,
    name: AVANCA_EVENT.shortTitle,
    summary: 'Perguntas e respostas inspiradas na nova arquitetura educacional: diagnóstico, recomposição, MAC e próximos passos.',
    accent: 'from-blue-900 via-slate-700 to-red-500',
    badge: 'Evento especial',
    icon: 'landmark',
    eventKey: AVANCA_EVENT_KEY,
    build: buildAvancaEventSlides,
  },
  {
    id: 'pitch',
    name: 'Apresentação de projeto',
    summary: 'Apresente uma ideia e ouça a avaliação de quem participa.',
    accent: 'from-brand-500 to-violet-600',
    badge: 'Projetos',
    icon: 'rocket',
    build: () => [
      ot('Em uma frase: qual problema você precisa resolver hoje?'),
      mc('Qual funcionalidade entrega mais valor para você?', [
        'Onboarding guiado',
        'Colaboração em tempo real',
        'Automação de tarefas',
        'Análise de dados avançada',
      ]),
      wc('Em uma palavra, qual sensação esse produto te causa?'),
      ot('Deixe um feedback para o time de produto'),
    ],
  },
  {
    id: 'kickoff',
    name: 'Abertura de encontro',
    summary: 'Conheça as expectativas do público antes de começar.',
    accent: 'from-brand-500 via-violet-500 to-ocean-500',
    badge: 'Encontros',
    icon: 'flag',
    build: () => [
      mc('Em uma escala de 0 a 10, qual a probabilidade de você recomendar este evento?', [
        '0–3', '4–6', '7–8', '9–10',
      ]),
      ts('Em qual grupo você quer participar?', [
        { name: 'Pesquisa', capacity: 12 },
        { name: 'Tecnologia', capacity: 14 },
        { name: 'Educação', capacity: 10 },
        { name: 'Comunicação', capacity: 8 },
      ]),
      wc('Qual palavra define o que você espera deste encontro?'),
      ot('Qual pergunta você quer trazer para a conversa?'),
    ],
  },
  {
    id: 'lecture',
    name: 'Aula Expositiva',
    summary: 'Engaje turmas grandes com votação, nuvem de conceitos e perguntas.',
    accent: 'from-violet-500 to-violet-700',
    badge: 'Educação',
    icon: 'book',
    build: () => [
      mc('Antes da aula, qual seu nível de familiaridade com o tema?', [
        'Nunca vi', 'Já ouvi falar', 'Conheço bem', 'Domino o assunto',
      ]),
      wc('Liste um conceito-chave que você lembra do último encontro'),
      ot('Qual dúvida ainda ficou em aberto?'),
      mc('Depois da aula, qual seu nível de familiaridade com o tema?', [
        'Nunca vi', 'Já ouvi falar', 'Conheço bem', 'Domino o assunto',
      ]),
    ],
  },
  {
    id: 'workshop',
    name: 'Oficina colaborativa',
    summary: 'Reúna ideias, forme os grupos e defina os próximos passos.',
    accent: 'from-sunset-500 to-coral-600',
    badge: 'Workshops',
    icon: 'wrench',
    build: () => [
      wc('Quais temas trazem você até este workshop?'),
      ts('Em qual mesa você quer se sentar?', [
        { name: 'Mesa de ideias', capacity: 6 },
        { name: 'Mesa de pesquisa', capacity: 6 },
        { name: 'Mesa de execução', capacity: 6 },
      ]),
      mc('Quão provável você está de aplicar algo nas próximas 72h?', [
        'Nada provável', 'Pouco provável', 'Provável', 'Muito provável',
      ]),
      ot('Qual será o seu próximo passo concreto?'),
    ],
  },
  {
    id: 'retro',
    name: 'Retrospectiva',
    summary: 'Coletar aprendizados, próximos passos e satisfações do time.',
    accent: 'from-ocean-500 to-ocean-700',
    badge: 'Times',
    icon: 'cycle',
    build: () => [
      ot('Qual foi seu maior aprendizado deste ciclo?'),
      mc('Como você avaliaria a colaboração do time?', [
        'Pode melhorar', 'Boa', 'Excelente', 'Extraordinária',
      ]),
      wc('Em uma palavra, descreva o próximo ciclo'),
      mc('Qual prioridade você quer levar para o próximo ciclo?', [
        'Foco total', 'Colaboração', 'Experimentação', 'Pausa estratégica',
      ]),
    ],
  },
  {
    id: 'townhall',
    name: 'Assembleia aberta',
    summary: 'Perguntas abertas, escala de humor e nuvem de expectativas.',
    accent: 'from-coral-500 to-coral-700',
    badge: 'Comunidade',
    icon: 'megaphone',
    build: () => [
      mc('Como está a sua energia hoje?', [
        '🔋 Carregado', '🙂 Bem', '😐 Neutro', '🔴 Desafiador',
      ]),
      ot('Qual tema você quer ver discutido nesta assembleia?'),
      wc('Em uma palavra, como você está se sentindo agora?'),
      mc('Você ficou satisfeito com as respostas da liderança?', ['Sim', 'Parcialmente', 'Não']),
    ],
  },
  {
    id: 'demo',
    name: 'Demo Day',
    summary: 'Avalie pitches, colete torcida e defina o projeto favorito.',
    accent: 'from-brand-600 via-violet-500 to-coral-500',
    badge: 'Demo Day',
    icon: 'trophy',
    build: () => [
      mc('Qual pitch mais chamou sua atenção?', [
        'Time 1 — Atlas', 'Time 2 — Pulsar', 'Time 3 — Órbita', 'Time 4 — Íris',
      ]),
      ts('Em qual time você quer votar?', [
        { name: 'Atlas', capacity: 30 },
        { name: 'Pulsar', capacity: 30 },
        { name: 'Órbita', capacity: 30 },
      ]),
      wc('Em uma palavra, qual pitch te surpreendeu?'),
      ot('Deixe um conselho para os times finalistas'),
    ],
  },
]

export const TEMPLATE_BY_ID = Object.fromEntries(TEMPLATES.map((t) => [t.id, t]))
